# Game settings
TITLE = "Tank Game"

WIDTH = 1280
HEIGHT = 720

FPS = 60

# Player/Tank
TANKSCALE = 0.75
TANK_HEALTH = 3

# Bullet/shooting
SHOOT_COOLDOWN = 20
BULLET_SCALE = 1
BULLET_SPEED = 5
BULLET_LIFETIME = 5

# grid
BACKGROUND_IMAGE = 'Assets/Maps/BasicTestBackground.png'
MAP_FILENAME = 'Assets/Maps/TextMap.txt'
TILESIZE = 32
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

# ui elements
BLUETANK_HEALTH_X = 100
BLUETANK_HEALTH_Y = 100
HEART_SCALE = 2

# colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
TAN = (234, 219, 198)